import React from 'react';
import DOMPurify from 'dompurify';
import { cn } from "@/lib/utils";

interface RichTextRendererProps {
  content: string;
  className?: string;
  isSmall?: boolean;
}

/**
 * RichTextRenderer safely renders HTML content generated by the Tiptap editor.
 * It uses DOMPurify for sanitization and Tailwind Typography (prose) for styling.
 */
export const RichTextRenderer: React.FC<RichTextRendererProps> = ({ 
  content, 
  className,
  isSmall = false 
}) => {
  if (!content) return null;

  // Sanitize HTML to prevent XSS
  const sanitizedHtml = DOMPurify.sanitize(content);

  return (
    <div 
      className={cn(
        "prose max-w-none transition-all duration-300",
        isSmall ? "prose-sm" : "prose-base sm:prose-lg",
        // Custom color overrides to match the brand identity if needed
        "prose-headings:text-foreground prose-p:text-muted-foreground prose-strong:text-foreground",
        "prose-li:text-muted-foreground prose-ul:list-disc prose-ol:list-decimal",
        className
      )}
      dangerouslySetInnerHTML={{ __html: sanitizedHtml }}
    />
  );
};
