const { ORDER_STATUS } = require('./orderStatus');

/**
 * Valid Next Transitions for Order Lifecycle
 */
const ALLOWED_TRANSITIONS = {
    [ORDER_STATUS.PENDING]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED_BY_ADMIN, ORDER_STATUS.CANCELLED_BY_CUSTOMER],
    [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED_BY_ADMIN, ORDER_STATUS.CANCELLED_BY_CUSTOMER],
    [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.PACKED, ORDER_STATUS.CANCELLED_BY_ADMIN, ORDER_STATUS.CANCELLED_BY_CUSTOMER],
    [ORDER_STATUS.PACKED]: [ORDER_STATUS.SHIPPED, ORDER_STATUS.CANCELLED_BY_ADMIN, ORDER_STATUS.CANCELLED_BY_CUSTOMER],
    [ORDER_STATUS.SHIPPED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.DELIVERY_UNSUCCESSFUL],
    [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.DELIVERY_UNSUCCESSFUL],
    [ORDER_STATUS.DELIVERY_UNSUCCESSFUL]: [ORDER_STATUS.DELIVERY_REATTEMPT_SCHEDULED, ORDER_STATUS.RTO_IN_TRANSIT],
    [ORDER_STATUS.DELIVERY_REATTEMPT_SCHEDULED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.RTO_IN_TRANSIT],
    [ORDER_STATUS.RTO_IN_TRANSIT]: [ORDER_STATUS.RETURNED_TO_ORIGIN],
    [ORDER_STATUS.RETURNED_TO_ORIGIN]: [ORDER_STATUS.REFUND_INITIATED],
    [ORDER_STATUS.DELIVERED]: [ORDER_STATUS.RETURN_REQUESTED],
    [ORDER_STATUS.RETURN_REQUESTED]: [ORDER_STATUS.RETURN_APPROVED, 'return_rejected'],
    [ORDER_STATUS.RETURN_APPROVED]: [ORDER_STATUS.PICKUP_SCHEDULED, 'return_cancelled'],
    [ORDER_STATUS.PICKUP_SCHEDULED]: [ORDER_STATUS.PICKUP_ATTEMPTED, ORDER_STATUS.PICKUP_FAILED, ORDER_STATUS.PICKUP_COMPLETED],
    [ORDER_STATUS.PICKUP_ATTEMPTED]: [ORDER_STATUS.PICKUP_SCHEDULED, ORDER_STATUS.PICKUP_FAILED],
    [ORDER_STATUS.PICKUP_FAILED]: [ORDER_STATUS.DELIVERED],
    [ORDER_STATUS.PICKUP_COMPLETED]: [ORDER_STATUS.IN_TRANSIT_TO_WAREHOUSE],
    [ORDER_STATUS.IN_TRANSIT_TO_WAREHOUSE]: [ORDER_STATUS.PARTIALLY_RETURNED, ORDER_STATUS.RETURNED]
};

const OrderStateMachine = {
    /**
     * Check if a transition is valid and if guards pass
     */
    canTransition: (currentStatus, nextStatus) => {
        const allowed = ALLOWED_TRANSITIONS[currentStatus] || [];
        return allowed.includes(nextStatus);
    }
};

module.exports = OrderStateMachine;
