/**
 * Refund Status Domain
 */
const REFUND_STATUS = {
    NOT_STARTED: 'NOT_STARTED',
    REFUND_INITIATED: 'REFUND_INITIATED',
    RAZORPAY_PROCESSING: 'RAZORPAY_PROCESSING',
    REFUNDED: 'REFUNDED',
    FAILED: 'FAILED'
};

const REFUND_TERMINAL = [REFUND_STATUS.REFUNDED, REFUND_STATUS.FAILED];

module.exports = { REFUND_STATUS, REFUND_TERMINAL };
